2021-06-16 05:13:53,696 - gravity_core.wlogger - ERROR - Ошибка в работе оператора!
2021-06-16 05:13:53,699 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "wlauncher.py", line 54, in _start
    self.gravity_core.work()
  File "/home/qodex/Gravity_core_export/gravity_core/wengine.py", line 1183, in work
    subscribe_ce(self.sock)
  File "/home/qodex/Gravity_core_export/gravity_core/functions/skud_funcs.py", line 18, in subscribe_ce
    sleep(1)
KeyboardInterrupt

2021-06-16 05:26:05,601 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-16 05:26:06,721 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 06:50:47,260 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-16 06:50:53,192 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 06:51:02,653 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 08:49:04,018 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-16 08:49:04,022 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 08:49:04,039 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 09:39:42,436 - gravity_core.wlogger - ERROR - Ошибка в работе оператора!
2021-06-16 09:39:42,437 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "wlauncher.py", line 54, in _start
    self.gravity_core.work()
  File "/home/qodex/Gravity_core_export/gravity_core/wengine.py", line 1183, in work
    subscribe_ce(self.sock)
  File "/home/qodex/Gravity_core_export/gravity_core/functions/skud_funcs.py", line 18, in subscribe_ce
    sleep(1)
KeyboardInterrupt

2021-06-16 11:32:45,129 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-16 11:32:45,204 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 11:32:45,220 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 13:41:50,890 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-16 13:41:50,942 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 13:41:50,958 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 13:41:50,960 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 13:54:36,328 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-16 13:54:36,399 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 13:54:36,417 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-16 13:54:36,419 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-17 05:21:49,377 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-17 05:21:49,448 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-17 05:21:49,465 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-17 05:35:08,761 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-17 05:35:08,833 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-17 05:35:08,850 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-17 14:33:47,453 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-17 14:33:47,502 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-17 14:33:47,519 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-17 14:33:47,521 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-18 05:29:14,217 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-18 05:29:14,268 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-18 05:29:14,285 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-19 05:07:39,831 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-06-19 05:07:39,883 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-19 05:07:39,900 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-06-19 05:07:39,900 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

