2021-07-01 19:32:41,753 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-07-01 19:32:41,803 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-01 19:32:41,824 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-01 19:32:41,824 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,119 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-07-02 08:12:09,120 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-07-02 08:12:09,120 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-07-02 08:12:09,121 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-07-02 08:12:09,122 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-07-02 08:12:09,122 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-07-02 08:12:09,123 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-07-02 08:12:09,123 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-07-02 08:12:09,124 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-07-02 08:12:09,169 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,169 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,170 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,172 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,172 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,173 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,173 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,174 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,174 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,188 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,188 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,189 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,189 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,189 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,190 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,190 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,190 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,191 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-07-02 08:12:09,193 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/qodex/Gravity_core_export/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

